version: "3.3"
services:
    mongodb:
        image : mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ../mongodb/database:/data/db
        restart: unless-stopped

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.14
        container_name: elasticsearch
        volumes:
            - ../elasticsearch:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        restart: unless-stopped

    openrasp:
        depends_on:
            - mongodb
            - elasticsearch
        build: .
        container_name: OpenRASP
        ports:
            - 8086:8086
        restart: always
        command: "/rasp-cloud-2021-02-07/rasp-cloud"
